#!/bin/sh
# url
url=`git config --get remote.origin.url`
url=${url/git@/http:\/\/}
url=${url//:/\/}
url=${url/\/\/\//:}
url=${url/\.git/\/}
url="${url}merge_requests/new?merge_request[target_branch]=master&merge_request[source_branch]=$(git rev-parse --abbrev-ref HEAD)"
url=${url//\#/\%23}

# open
open -a "Google Chrome" $url
