#!/bin/sh

# url
origin=`git config --get branch.master.remote`
url=`git config --get remote.${origin}.url`
url=${url/git@/http:\/\/}
url=${url//:/\/}
url=${url/\/\/\//:}
url=${url/\.git/\/}
url="${url}merge_requests/new?merge_request[target_branch]=fast&merge_request[source_branch]=$(git rev-parse --abbrev-ref HEAD)"

# open
open -a "Google Chrome" $url
